.editorconfig, .gitignore, README.md, examples/cloudwatch-alerts-to-slack/README.md, examples/cloudwatch-alerts-to-slack/main.tf, examples/cloudwatch-alerts-to-slack/outputs.tf, examples/notify-slack-kms/README.md, examples/notify-slack-kms/main.tf, examples/notify-slack-kms/outputs.tf, examples/notify-slack-simple/main.tf, functions/notify_slack.py, iam.tf, main.tf, outputs.tf, variables.tf
=> Updates in progress

README.md, examples/cloudwatch-alerts-to-slack/main.tf, examples/notify-slack-kms/main.tf, functions/notify_slack.py, main.tf, variables.tf
=> Fix Lambda path in shared state

functions/notify_slack.py
Instead of dropping the message subject, capture it and send to default_notification.
Default behavior will be unchanged if no subject is provided.
=> Pass the SNS subject to default_notification

main.tf
Terraform 0.12 syntax for depends_on
=> use 0.12 syntax for depends_on

.gitignore, README.md, functions/notify_slack.py, functions/notify_slack_test.py, functions/pytest.ini.sample, functions/requirements.txt, main.tf, variables.tf
Heavily based on #27 by @jinnko
=> Added pytest and logging

functions/notify_slack.py, functions/notify_slack_test.py
=> Added support for multiline messages

.gitignore, iam.tf
This PR aims to solve an opened [issue](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/issues/63)
=> Fix empty tuple error

README.md, main.tf, variables.tf
=> Add subscription filter policy support

stale.yml
Add Stale Bot Config
Already Configured Bot for this repo
=> feat: Add Stale Bot Config

.github/stale.yml
=> fix: Label issues only

main.tf, variables.tf
Add an option to enable SSE on the SNS Topic this module can create
We operate in environments with policies that all resources that support SSE must have it enabled
None. Defaults to existing behavior if this new variable is not provided
Deployed into several environments from our fork with no issues
Thanks for all the hard work on this module ❤️
=> feat: Add support for SSE on the topic

README.md, versions.tf
update required version of aws provider to allow 3.0. Fixes #93
=> feat: update required version of aws provider to allow 3.0

README.md, versions.tf
=> fix: Updated version requirements to be Terraform 0.13 only

main.tf
=> feat: Updated version of terraform-aws-lambda module to 1.28.0

.gitignore, README.md, examples/cloudwatch-alerts-to-slack/README.md, examples/cloudwatch-alerts-to-slack/main.tf, examples/cloudwatch-alerts-to-slack/versions.tf, main.tf, variables.tf
- feat: Allow Lambda function to be VPC bound
- Allow storing the lambda function in S3
Closes #121
=> feat: Allow Lambda function to be VPC bound

.github/workflows/pre-commit.yml, README.md, examples/cloudwatch-alerts-to-slack/README.md, examples/notify-slack-simple/README.md
- add ci-cd workflow for pre-commit checks
- provide static checks for pull requests
- no
- copy of what is implemented in SQS module repository
=> chore: add ci-cd workflow for pre-commit checks

.github/workflows/pre-commit.yml, README.md, main.tf
This PR updates the lambda module version and stops using Terraform functions that were deprecated.
This fixes issue #135 .
N/A
=> feat: Updated code to support Terraform 0.15

README.md, main.tf, variables.tf
Added policy path variable to lambda module IAM role policy
We need the path variable for the policy created by lambda module
no breaking change
I have tested and validated these changes using this branch
=> feat: Added policy path variable to lambda module IAM role policy

.pre-commit-config.yaml, README.md, main.tf, variables.tf
- add support for recreating package locally if not missing/not present
- Closes #148
- No
=> feat: add support for recreating package locally if not missing/not present

README.md
This updates the usage configuration example in the README to reflect the latest major version of this module.
Previously, the example config would install `v4.x.x` (e.g. `v4.24.0`).
No breaking change, but the rest of the 
Used the config in my own local project and ran `terraform init`.
=> docs: Update version in README example config

.github/workflows/pre-commit.yml, functions/events/guardduty_finding_high.json, functions/events/guardduty_finding_low.json, functions/events/guardduty_finding_medium.json, functions/messages/guardduty_finding.json, functions/mylambda.py, functions/notify_slack.py, functions/snapshots/snap_notify_slack_test.py
Always show the AWS AccountID that the GuardDuty event is related to.
I've modified the sample events and messages to add a bogus `accountId`. Running the `pipenv` commands as per the `README` made some formatting changes on `mylambda.py`, so I am leaving that as suggested by that run.
The snapshots also needed updating to reflect the fact that we now have an AccountID in the GuardDuty event/message.
It's my first contribution to this repo, so apologies in advance 😄 
This PR was motivated by the same reasoning I saw in https://github.com/terraform-aws-modules/terraform-aws-notify-slack/issues/164. We are using this module to send notifications from multiple AWS accounts to Slack and not having the AccountID visible in the notification was bugging us, as it makes the investigation slightly …
=> feat: Add account ID to GuardDuty event notification
