terraform-aws-modules/terraform-aws-notify-slack

main.tf

The `last_modified` timestamp is tied to when a user did a `terraform init`. This means the exact same code, checked out at different times, results in a change being detected. Ignoring the timestamp fixes this.
Changes to the function will still be detected like:
```
~ module.notify_slack_alerts.aws_lambda_function.notify_slack
source_code_hash:                 "Y8yIL83IwWZAe4hqFlfZnXIkK27kRDm1ihkbsy9vuek=" => "U4ExxA5bGa7s1wQxb3uHUZTZZ3ONTd85Ba4DMYk7DqI="
```

Ignore `last_modified` timestamp deciding whether to do an update (fixes #6)

---

README.md
functions/notify_slack.py
main.tf
variables.tf

I added in some slack emoji support instead of using the default webhook icon.

Add in slack emoji support

---

iam.tf
main.tf
outputs.tf
variables.tf

When this module is used with terraform workspaces we may choose to
enable/disable creation of resources based on various conditions.  Since
terraform modules don't support the count attribute we must pass in the
parameter and apply it to each resource within the module.
Unfortunately we also need to perform magic around various references to
paramaters for each resource when it doesn't get created.  We do this by
applying defaults with a combination of interpolation functions in a
very hacky way.  Not something to be proud of.

Add flag to enable/disable creation of resources

---

functions/notify_slack.py

Provide a bit of context to notifications by including the shortname in the notification text

include short alarm name in slack notification text

---

main.tf

The concat operation removes the empty string from the concatenated list, meaning that when create = false, the element operator tries to index into item 0 of a zero length list. This change fixes it so that when create = false, the apply will succeed with an empty value being computed for local.sns_topic_arn

Fixed bug which causes apply failure when create = false

---

functions/notify_slack.py

The value of `event['Records'][0]['Sns']['Message']` is a json string, not a dictionary.  I was getting this error prior to making the change:
string indices must be integers: TypeError
Traceback (most recent call last):
File "/var/task/notify_slack.py", line 79, in lambda_handler
notify_slack(subject, message, region)
File "/var/task/notify_slack.py", line 64, in notify_slack
payload['text'] = "AWS CloudWatch notification - " + message["AlarmName"]
TypeError: string indices must be integers

need to convert from json string to dict when extracting message from event

---

README.md
iam.tf
main.tf
variables.tf

The organization I work for requires that we tag all of our AWS resources, so I'd love to get tags wired up for this module! Otherwise, we'll have to fork it 😉 
I pretty much just copied what you have here: https://github.com/terraform-aws-modules/terraform-aws-vpc.

Add support for resource tagging

---

README.md
examples/notify-slack-simple/README.md
examples/notify-slack-simple/outputs.tf
iam.tf
main.tf
outputs.tf
variables.tf

The resources deployed by this module mimics the experience when creating Lambda functions in the console. The function gets created with an IAM role attached which allows it to put logs and create groups/streams anywhere; even places it's not supposed to. When the function creates the log group with it's built-in permissions this happens outside of Terraform. When you destroy the module a log group will remain and become stale because it's never tracked by Terraform's state in this way.
This PR adds a Cloudwatch Logs group and adds an explicit dependency on the function so that it will only be created when the log group is made (to prevent a race condition). It also adjusts the policy of the function to explicitly allow only log events on the Terraform managed log group.

Create AWS Cloudwatch log group and give explicit access to it

---

iam.tf

The IAM policy for the Lambda was *:*:* which seems like it was more permissive than necessary.  This PR will reduce the scope to having the wildcard "${var.lambda_function_name}:log-stream:*" instead of all Cloudwatch logs.  This should be a non-breaking change that has been tested with Terraform 0.11.14.

Reduce scope of IAM Policy for CloudWatch Logs

---

functions/notify_slack.py

Alarm names with spaces produce links that are not recognized by the AWS console:
Method [`#quote_plus`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote_plus) replace spaces by plus sign which AWS does not recognize. Using [`#quote`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote) replaces spaces with percent escaping (`%20`).

Use urllib.parse.quote for the alarm name

---

main.tf

Use lambda module version that supports Terraform 13 and AWS provider 3.x
Fixes #93
N/A
* Ran` pre-commit run -a`
* Ran `terraform init`
* Ran `terraform validate`

fix: Bump version of lambda module

---

main.tf

fix: Fix regression with aws_cloudwatch_log_group resource after upgrade of AWS provider 3.0

---

.pre-commit-config.yaml
CHANGELOG.md
README.md
examples/cloudwatch-alerts-to-slack/README.md
examples/cloudwatch-alerts-to-slack/versions.tf
examples/notify-slack-simple/README.md
examples/notify-slack-simple/versions.tf
main.tf
variables.tf
versions.tf

Resolving the typo in the input parameter name: `subsription_filter_policy` as described in the issue #112 
Changed `subsription_filter_policy` to `subscription_filter_policy` everywhere it's used
It makes the parameter name consistent with aws terms
[https://github.com/terraform-aws-modules/terraform-aws-notify-slack/issues/112](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/issues/112)

fix: Typo on subscription_filter_policy variable

---

functions/notify_slack.py

Like many things in GovCloud, things are slightly different than in commercial AWS. This PR adds support for generating CloudWatch URL in AWS accounts in GovCloud. 
Without this change, CloudWatch URLs generated in GovCloud won't work correctly. 
No breaking changes. 
I followed the docs and created a custom pytest.ini and ran pytests to confirm.

feat: add support for GovCloud URLs

---

.gitignore
.pre-commit-config.yaml
README.md
examples/cloudwatch-alerts-to-slack/README.md
examples/notify-slack-simple/README.md

- update documentation based on latest `terraform-docs` which includes module and resource sections
- `.gitignore` updated using GitHub provided default standard + 0.14 lockfile ignore
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)
No
N/A

chore: update documentation based on latest `terraform-docs` which includes module and resource sections

---

functions/notify_slack.py
functions/notify_slack_test.py

Improves readability of generic messages sent by AWS services.
Before this PR:
With this PR:
Currently messages other than the ones from Cloudwatch are sent as slack messages in verbatim as json strings. I thought by formatting the messages it would enhance its readability. For instance, this happens to messages received from AWS DMS events.
No breaking changes
Ran existing test according to test setup instructions. Existing tests fixtures already provide coverage and this change only affects the formatting of the default notification.

feat: Improve slack message formatting for generic messages

---

README.md
main.tf

This PR re-enables deployment of this module to AWS partitions outside of `aws`. This fixes an issue introduced as a byproduct of https://github.com/terraform-aws-modules/terraform-aws-notify-slack/commit/2c4f15bf48cd96dd55a27faf4e0f5376b2c30268, where previously the partition ARN was dynamically identified through the use of the https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/sns_topic resource.
Instead of hardcoding to the `aws` partition, this PR re-enables dynamic identification of the current partition through the use of the https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/partition resource.
Without this PR, I see this error when applying changes that use v4.12.0 of this module:
```text
Error: error creating SNS topic …
```

fix: use the current aws partition

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
README.md
examples/cloudwatch-alerts-to-slack/README.md
examples/notify-slack-simple/README.md

- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks

chore: update documentation and pin `terraform_docs` version to avoid future changes

---

.gitignore
functions/notify_slack.py
functions/notify_slack_test.py
functions/pytest.ini

- Supersedes the following stale PR: https://github.com/terraform-aws-modules/terraform-aws-notify-slack/pull/47
Takes the same idea and code and adds a test case for it as requested in the original PR.
- If `attachments` or `text` is found within the event it is assumed that the event follows the slack [message specification](https://api.slack.com/reference/messaging/attachments#fields) and is merged as is with the payload sent to slack.
- Additionally removes and ignores the non default `pytest.ini`.
The default message is not customizable and can be hard to read if there are a lot of fields included.
Knowing the slack API requirements a user should be able to customize the message displayed in slack according to their needs. 
None identified.
Added the [slack message with attachment …

feat: Allow custom attachement

---

README.md
functions/notify_slack.py
functions/notify_slack_test.py

This adds formatting for Guardduty Findings.  This is based on #127 but resolving the feedback and adding tests.  Thank you to @iogi for their original contribution I just want to see this to the finish line.
The Guard Duty findings were not properly reported in this module and were hidden away in the details of this SNS event structure.
NO
* I have tested this in a test and an few customer environments
* I have added a test into the pytest to validate the formatting is working properly
Closes #127

feat: Added support for GuardDuty Findings format

---

README.md
main.tf
variables.tf

Role path is needed for IAM role created by lambda module
We use permission boundaries tied to IAM role path in our environment. This is required for us
No breaking change
This has been tested on this branch

feat: Added path input variable for lambda module IAM role 

---

.github/workflows/pr-title.yml
README.md
outputs.tf

feat: Revert incorrectly removed output this_slack_topic_arn

---

README.md
examples/cloudwatch-alerts-to-slack/README.md
examples/cloudwatch-alerts-to-slack/versions.tf
examples/notify-slack-simple/README.md
examples/notify-slack-simple/versions.tf
main.tf
versions.tf

Due to the breaking changes in AWS provider 4.x, the lambda module used as part of this module has been updated to 3.x to support the new provider. To allow this module to be used with the new provider, we need to update the lambda module version.
This updates the dependent lambda module to version 3.x, allowing this module to be used with AWS provider 4.x.
This is a breaking change as it is no longer compatible with AWS provider 3.x.

feat!: Update lambda module to 3.1.0 to support AWS provider version 4.8+

---

README.md
main.tf
variables.tf

When using this module in GovCloud, we get this error (this is sanitized):
```
│ Error: error modifying Lambda Function (lambda-name) configuration : InvalidParameterValueException: Ephemeral storage configuration ('ephemeralStorage') is currently not supported. Please remove the ephemeral storage parameter from your request and try again.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "..."
│   },
│   Message_: "Ephemeral storage configuration ('ephemeralStorage') is currently not supported. Please remove the ephemeral storage parameter from your request and try again.",
│   Type: "User"
│ }
```
This was fixed in 3.1.1 of terraform-aws-lambda: https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/304#issuecomment-1098448429
This PR does two things:
1. …

feat: Add ephemeral_storage_size variable

---

functions/events/aws_health_event.json
functions/notify_slack.py
functions/snapshots/snap_notify_slack_test.py

AWS Health Event formatting was added to the script. Now it is possible to configure Event Bridge to send messages to the SNS topic and messages will be formatted and sent to the slack channel.
It is a new feature that allows formatting the AWS Health messages.
-  I have tested and validated these changes using notify-slack-simple example
- I have executed `pre-commit run -a` on my pull request

feat: Added support for AWS Health events

---

.github/workflows/lock.yml
.github/workflows/pr-title.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/stale-actions.yaml
.github/workflows/unit-test.yml

- Update GitHub action versions to use latest. This remove warnings related to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- Ensure pre-commit config is aligned with latest
- Add `lock.yml` workflow to automatically lock issues and PRs after 30 days. Theres a lot "Me too" or "I have this issue, when will this get fixed" on really old/stale issues and in order to properly triage, users need to supply their configurations. This workflow is pulled from the AWS provider's repo to force users to fill out a proper issue ticket and keep chatter out of merged PRs or old issues
- Patch warnings on CI checks to keep output clean
- Focus on new issues and PRs
- No

fix: Update CI configuration files to use latest version

---

README.md
examples/cloudwatch-alerts-to-slack/main.tf
iam.tf
main.tf
outputs.tf
variables.tf

The purpose of this pull request is to add delivery status logging for the SNS topic. This is achieved by specifying an IAM role with permission to write to CloudWatch logs. If a role is not specified, then a role will be created - if delivery logging is required.
I recently worked on a project which required compliance with [NCSC Operational Best Practices](https://docs.aws.amazon.com/config/latest/developerguide/operational-best-practices-for-ncsc.html). SNS delivery status logging must be enabled to comply with this framework. I created the topic outside of the module initially, but thought it would be a useful addition to the module.
- :white_check_mark: I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- :white_check_mark: I have tested and …

feat: Add SNS topic delivery status IAM role

---

.github/workflows/lock.yml
.github/workflows/release.yml
.github/workflows/unit-test.yml

The `Release`, `Unit test` and `Lock` workflow are using an old version and hence a [deprecated runtime (Node.js 12)](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). Bumping these workflows will resolve the deprecation warning in the affected workflows.
Make sure that CI workflows uses non-deprecated runtimes.
None.

chore: Upgrade CI workflows to use non-deprecated runtimes

---

.pre-commit-config.yaml
README.md
examples/cloudwatch-alerts-to-slack/README.md
examples/cloudwatch-alerts-to-slack/versions.tf
examples/notify-slack-simple/README.md
examples/notify-slack-simple/versions.tf
main.tf
variables.tf
versions.tf

Add variable for passing filter_policy_scope
I want to filter body of message on SNS level.

feat!: Added variable to filter body of message on SNS level and bumped min Terraform version to 1.0

---

README.md
main.tf
variables.tf

This PR adds a `hash_exta` variable and passes it to the Lambda module. This is useful when this module is called more than once in a workspace. Multiple zip file creations can overlap, causing corruption. 
- Resolves #210
Does not break anything, hash_extra defaults to `""`

feat: Expose `hash_extra` variable from Lambda module

---

.pre-commit-config.yaml
iam.tf

Replaced the defined `assume_role_policy` with an inline policy and with that the IAM policy for CloudWatch Logs is properly attached to the role, and a valid assume role policy is defined, granting AWS SNS the right to assume the role.
Fixes #219

fix: Correct assume role permissions for SNS service to assume IAM role

---

.github/workflows/unit-test.yml
README.md
functions/.pyproject.toml
functions/Pipfile
main.tf

- Update Python lambda runtime from `3.8` to `3.11`
- I tried `3.12` but there is more work involved there to support that so this seemed like a good compromise 
- Python 3.8 runtime is deprecated and will be EOL later this year
- Resolves #217 
- No

feat: Update Python lambda runtime from `3.8` to `3.11`

---

README.md
main.tf

This commit updates the `aws_sns_topic_subscription` resource to use the `lambda_function_qualified_arn` output for the `endpoint` value.
Also bump the `lambda` module to `6.8.0`, which is the latest version that maintains compatability with `aws` v4 provider.
Fixes: #230
None

fix: Update `aws_sns_topic_subscription` endpoint to use qualified arn

---

README.md
main.tf
variables.tf

This adds a variable (default false) for triggering an update of the underlying lambda based on the timestamp of the underlying file
This fixes the case where this module is used and automatically planned/applied from CI, where the source is freshly copied/cloned - currently, the module will always attempt to update the lambda in this case!
Fixes #232
~~This does bump the underlying `terraform-aws-modules/terraform-aws-lambda` version from `3.2.0` -> `6.7.0` (the minimum that supports this option) - but the only breaking changes I can see from that are that only `terraform >= 1` is supported, and it requires a slightly newer AWS provider~~
This originally bumped the version of the lambda module from `3.2.0` -> `6.7.0` - but master has changed to `6.8.0`!
I have used this in my fork of the …

feat: Add variable to allow disabling the package timestamp trigger

---

.github/workflows/pr-title.yml
.github/workflows/pre-commit.yml
.pre-commit-config.yaml
README.md
examples/cloudwatch-alerts-to-slack/README.md
examples/notify-slack-simple/README.md

- Update CI workflow versions to latest
- Updates our workflows to use the latest versions
- Removes warnings for Python 3.12 in runners
- No

fix: Update CI workflow versions to latest

---

main.tf

Reverts a change made in https://github.com/terraform-aws-modules/terraform-aws-notify-slack/commit/e95cde8acdaf221e74595daa2238b75f0682ea06 where a variable was changed, breaking SNS topic subscriptions.
Fixes https://github.com/terraform-aws-modules/terraform-aws-notify-slack/issues/238 
No

fix: Reverts endpoint variable change from e95cde8

---

functions/notify_slack.py

Logging is being flagged by AWS Inspector for log injection
Log injection fix
No
- [x ] I have tested and validated these changes using one or more of the provided `examples/*` projects
Veriified by updating on existing lambda and seeing the lambda issue clear in Inspector
- [ x] I have executed `pre-commit run -a` on my pull request

fix: Modify logging for security inspector issue

---

README.md
functions/notify_slack.py
main.tf
variables.tf

- In Lambda function coded added logger initialized with default log level = INFO
- Created dedicated variable to allow users to set lambda log level
- Minor changes to README file
- Resolves #253 
No breaking changes, only fixes and minor improvements.

fix: Ensure logger is initialized correctly and propagate `log_level` variable to `LOG_LEVEL` environment variable
